# Generated by Django 5.2 on 2025-05-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="floorplan",
            old_name="plan",
            new_name="file",
        ),
    ]
