# Generated by Django 5.2 on 2025-05-14 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="land_area",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="rooms",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="square",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="details",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="equipment",
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(blank=True, upload_to="media_files/")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
