# Generated by Django 5.2 on 2025-05-16 11:24

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_rename_plan_floorplan_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="banner_image",
            field=models.FileField(
                blank=True, upload_to=projects.models.media_file_path
            ),
        ),
    ]
