# Generated by Django 5.2 on 2025-05-16 11:33

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_banner_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="banner_image",
            field=models.FileField(
                blank=True, upload_to=projects.models.banner_image_path
            ),
        ),
    ]
