# Generated by Django 5.2 on 2025-05-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_project_banner_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="latitude",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="longitude",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
