# Generated by Django 5.2 on 2025-06-24 10:29

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_latitude_project_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="video",
            field=models.FileField(
                blank=True, upload_to=projects.models.media_file_path
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_status",
            field=models.CharField(
                choices=[("F", "Future"), ("A", "Actual"), ("P", "Past")],
                default="F",
                max_length=1,
            ),
        ),
    ]
