# Generated by Django 5.2 on 2025-06-24 11:14

import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_mediafile_video_project_project_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediafile",
            name="video",
        ),
        migrations.CreateModel(
            name="VideoFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, upload_to=projects.models.media_file_path
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_video",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
