# Generated by Django 5.2 on 2025-06-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_remove_mediafile_video_videofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="expose",
            field=models.FileField(
                blank=True, upload_to="project_<built-in function id>/"
            ),
        ),
    ]
