# Generated by Django 5.2 on 2025-06-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_project_expose"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="project_status",
            new_name="status",
        ),
        migrations.AlterField(
            model_name="project",
            name="expose",
            field=models.FileField(blank=True, upload_to="expose/"),
        ),
    ]
