# Generated by Django 5.2 on 2025-06-18 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomePageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_description", models.TextField()),
                ("about_us", models.TextField(blank=True, null=True)),
                ("address", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="AboutUsMediaContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="homepage_slides/about_us_slides"
                    ),
                ),
                (
                    "homepage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about_us_slides",
                        to="home.homepagecontent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MainTitleMediaContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="homepage_slides/main_title_slides"
                    ),
                ),
                (
                    "homepage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_title_slides",
                        to="home.homepagecontent",
                    ),
                ),
            ],
        ),
    ]
